CREATE DATABASE Family
USE Family

CREATE TABLE Member (
	id INT PRIMARY KEY IDENTITY(1,1),
	fn VARCHAR(62),
	mn VARCHAR(62),
	ln VARCHAR(62),
	dn VARCHAR(30),
	dob DATETIME,
	note VARCHAR(2000),
	crt DATETIME NOT NULL DEFAULT GETDATE(),
	upd DATETIME
)
GO

CREATE TABLE Relationship (
	Id INT PRIMARY KEY IDENTITY(1,1),
	MemberId INT NOT NULL,
	RelationshipId INT NOT NULL,
	[Type] VARCHAR(30) NOT NULL,
	Note VARCHAR(2000)
)
GO

CREATE TABLE Tree (
  id INT PRIMARY KEY IDENTITY(1,1),
  title VARCHAR(126) NOT NULL,
  crt DATETIME NOT NULL,
  upd DATETIME NOT NULL
)
GO

CREATE TABLE TreeItem (
  id INT PRIMARY KEY IDENTITY(1,1),
  treeId INT,
  mbrId INT,
  x INT NOT NULL,
  y INT NOT NULL,
  crt DATETIME NOT NULL DEFAULT(GETDATE()),
  upd DATETIME NOT NULL DEFAULT(GETDATE()),
  CONSTRAINT FK_TreeItemTreeRef FOREIGN KEY (treeId) REFERENCES Tree(id),
  CONSTRAINT FK_TreeItemMemberRef FOREIGN KEY (mbrId) REFERENCES [Member](id)
)
GO