CREATE TABLE TreeItem (
  id INT PRIMARY KEY IDENTITY(1,1),
  treeId INT,
  mbrId INT,
  x INT NOT NULL,
  y INT NOT NULL,
  crt DATETIME NOT NULL DEFAULT(GETDATE()),
  upd DATETIME NOT NULL DEFAULT(GETDATE()),
  CONSTRAINT FK_TreeItemTree FOREIGN KEY (treeId) REFERENCES Tree(id),
  CONSTRAINT FK_TreeItemMember FOREIGN KEY (mbrId) REFERENCES [Member](id)
)